FROM ubuntu:16.04

WORKDIR /crawler

RUN apt-get update
RUN apt-get install apt-transport-https python2.7 -y

RUN echo "deb [trusted=yes] https://repo.iovisor.org/apt/xenial xenial-nightly main" | tee /etc/apt/sources.list.d/iovisor.list
RUN apt-get update 
RUN apt-get install bcc-tools -y
RUN apt-get install libbcc-examples -y
ENV PYTHONPATH=/usr/lib/python2.7/dist-packages/

COPY requirements.txt /crawler/requirements.txt
RUN apt-get install python-setuptools -y
RUN easy_install pip
RUN apt-get install python-dev gcc -y
RUN pip install -r requirements.txt

COPY \
  dependencies/python-socket-datacollector_0.1.3-1_all.deb \
  dependencies/softflowd_0.9.9902-1_amd64.deb \
  dependencies/python-conntrackprobe_0.2.0-1_all.deb \
  /tmp/

RUN dpkg -i /tmp/python-socket-datacollector_*_all.deb && \
    apt-get -y update && \
    apt-get -y install libpcap0.8 && \
    dpkg -i /tmp/softflowd_0.9.*_amd64.deb && \
    pip install pyroute2 py-radix requests-unixsocket json-rpc && \
    dpkg -i /tmp/python-conntrackprobe_*_all.deb && \
    rm -f /tmp/*.deb

ENV PYTHONPATH=/usr/lib/python2.7/dist-packages:/usr/local/lib/python2.7/site-packages

RUN apt-get install -y wget
RUN wget http://kernel.ubuntu.com/~kernel-ppa/mainline/v4.9/linux-headers-4.9.0-040900-generic_4.9.0-040900.201612111631_amd64.deb
RUN wget http://kernel.ubuntu.com/~kernel-ppa/mainline/v4.9/linux-headers-4.9.0-040900_4.9.0-040900.201612111631_all.deb
RUN dpkg -i *.deb
RUN rm -rf *.deb

ADD crawler /crawler

ENTRYPOINT [ "python2.7", "crawler.py" ]
